### ISSUE TITLE
make tabs visible

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-project-secure-coding-practices-quick-reference-guide#5]
At the moment the tabs 'downloads' and 'contributors' are not displayed

**Comment by jgadsden** [comment]
@PauloASilva did you want to take this on? I had similar trouble with the Threat Dragon pages so I can fix this if you want me to

**Comment by PauloASilva** [comment]
@jgadsden if you know what's wrong, please go ahead and push the fix.

If further debugging is required, having write permission to the repo would help, since I am not sure exactly how to build the website locally.

**Comment by jgadsden** [comment]
Hello @PauloASilva - I can take this one on, should be later on this evening

You have 'Maintain' permissions which is one down from Admin and one up from Write
